remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

title: "Aline Bertolani"
subtitle: "Análise e Ciência de Dados | Portfólio"
description: "Portfólio de Aline Gracioli Bertolani - Analista de Dados em desenvolvimento para área de Ciência de Dados"

# Links de redes sociais (aparecem no rodapé)
social_links:
  github: "https://github.com/alinebertolani"
  linkedin: "www.linkedin.com/in/alinegraciolibertolani"
  email: "alinegraciolibertolani@gmail.com"

# Navegação (menu no cabeçalho)
navbar:
  - name: "Início"
    link: "/"
  - name: "Sobre"
    link: "/sobre"
  - name: "Projetos"
    link: "/projetos"
  - name: "Contato"
    link: "/contato"

markdown: kramdown
