remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
description: "Seja bem vindo (a) ao meu Portfólio em Análise e Ciência de Dados"
lang: pt-BR
permalink: pretty
fixed_navbar: top

# URLs do site (para SEO e links corretos)
url: "https://alinebertolani.github.io"
baseurl: ""   # user site -> vazio

# Plugins whitelisted no GitHub Pages
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
